version: '3.8'

services:
  backend:
    entrypoint: /bin/true

  frontend:
    entrypoint: /bin/true

  mongo:
    container_name: mongo_dev_db
    volumes:
      - mongo-dev-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - backend-network

volumes:
  mongo-dev-data:


networks:
  backend-network:
    driver: bridge
